compute_precision:
  grad_scaler: false
  teacher:
    backbone:
      sharding_strategy: SHARD_GRAD_OP
      mixed_precision:
        param_dtype: bf16
        reduce_dtype: bf16
        buffer_dtype: bf16
    dino_head:
      sharding_strategy: SHARD_GRAD_OP
      mixed_precision:
        param_dtype: bf16
        reduce_dtype: bf16
        buffer_dtype: bf16
    ibot_head:
      sharding_strategy: SHARD_GRAD_OP
      mixed_precision:
        param_dtype: bf16
        reduce_dtype: bf16
        buffer_dtype: bf16
  student:
    backbone:
      sharding_strategy: SHARD_GRAD_OP
      mixed_precision:
        param_dtype: bf16
        reduce_dtype: bf16
        buffer_dtype: bf16
    dino_head:
      sharding_strategy: SHARD_GRAD_OP
      mixed_precision:
        param_dtype: bf16
        reduce_dtype: bf16
        buffer_dtype: bf16
    ibot_head:
      sharding_strategy: SHARD_GRAD_OP
      mixed_precision:
        param_dtype: bf16
        reduce_dtype: bf16
        buffer_dtype: bf16
dino:
  head_n_prototypes: 131072
  head_bottleneck_dim: 384
ibot:
  separate_head: true
  head_n_prototypes: 131072
train:
  batch_size_per_gpu: 32
  dataset_path: ImageNet22k
  centering: sinkhorn_knopp
  num_workers: 16
student:
  arch: vit_large
  patch_size: 14
  drop_path_rate: 0.4
  ffn_layer: swiglufused
  block_chunks: 4
teacher:
  momentum_teacher: 0.994
optim:
  epochs: 500
  weight_decay_end: 0.2
  base_lr: 2.0e-04
  warmup_epochs: 80
  layerwise_decay: 1.0
crops:
  local_crops_size: 98
